### ISSUE TITLE
unable to start the app

### ISSUE THREAD

**Issue by nandinicbit1981** [azazdeaz/rasa-nlu-trainer#8]
Getting the following exception : 

rasa-nlu-trainer/server.js:18
  pkg,
     ^
SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

**Comment by azazdeaz** [comment]
Hello @nandinicbit1981!

Thank you for reporting the issue. Which npm version are you using?

**Comment by nandinicbit1981** [comment]
Hello @azazdeaz 
I am using npm version 1.3.6

**Comment by azazdeaz** [comment]
Could you try updating your node/npm version?

**Comment by nandinicbit1981** [comment]
updated the version to 4.3.0 still getting the same exception.

**Comment by azazdeaz** [comment]
Are you also updated the node version? (you can check it with `node -v` it sould be above v6)
Also, you can make sure that you have the latest rasa-nlu-trainer by running `npm i -g rasa-nlu-trainer`
